package com.islandpower.configurator.model.project;

import java.util.List;

public class ProjectSolarPanel {
    private String solarPanelId; // Reference to the selected Solar Panel
    private int numberOfPanels; // Maximum number of panels needed in any month
    private double totalPowerGenerated; // Total power generated by the panels (Watt-hours)
    private double totalCost; // Total cost of the selected panels
    private double efficiencyLoss; // Efficiency loss due to temperature or other factors
    private double estimatedDailyEnergyProduction; // Estimated daily energy production (Wh)
    private List<MonthlySolarData> monthlyData; // Monthly data including PSH and ambientTemperature

    public ProjectSolarPanel() {
    }

    public ProjectSolarPanel(String solarPanelId, int numberOfPanels, double totalPowerGenerated, double totalCost,
                             double efficiencyLoss, double estimatedDailyEnergyProduction, List<MonthlySolarData> monthlyData) {
        this.solarPanelId = solarPanelId;
        this.numberOfPanels = numberOfPanels;
        this.totalPowerGenerated = totalPowerGenerated;
        this.totalCost = totalCost;
        this.efficiencyLoss = efficiencyLoss;
        this.estimatedDailyEnergyProduction = estimatedDailyEnergyProduction;
        this.monthlyData = monthlyData;
    }

    // Getters and Setters
    public String getSolarPanelId() {
        return solarPanelId;
    }

    public void setSolarPanelId(String solarPanelId) {
        this.solarPanelId = solarPanelId;
    }

    public int getNumberOfPanels() {
        return numberOfPanels;
    }

    public void setNumberOfPanels(int numberOfPanels) {
        this.numberOfPanels = numberOfPanels;
    }

    public double getTotalPowerGenerated() {
        return totalPowerGenerated;
    }

    public void setTotalPowerGenerated(double totalPowerGenerated) {
        this.totalPowerGenerated = totalPowerGenerated;
    }

    public double getTotalCost() {
        return totalCost;
    }

    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }

    public double getEfficiencyLoss() {
        return efficiencyLoss;
    }

    public void setEfficiencyLoss(double efficiencyLoss) {
        this.efficiencyLoss = efficiencyLoss;
    }

    public double getEstimatedDailyEnergyProduction() {
        return estimatedDailyEnergyProduction;
    }

    public void setEstimatedDailyEnergyProduction(double estimatedDailyEnergyProduction) {
        this.estimatedDailyEnergyProduction = estimatedDailyEnergyProduction;
    }

    public List<MonthlySolarData> getMonthlyData() {
        return monthlyData;
    }

    public void setMonthlyData(List<MonthlySolarData> monthlyData) {
        this.monthlyData = monthlyData;
    }

    // Inner class to store data for each month, including PSH and ambient temperature
    public static class MonthlySolarData {
        private int month; // 1-12
        private Double psh; // Peak Sun Hours (Allow null)
        private Double ambientTemperature; // Allow null
        private double totalDailyEnergy;
        private double requiredEnergy;
        private double requiredPower;
        private double temperatureEfficiency;
        private double efficiency;
        private double deratedPower;
        private int numPanels;
        private double estimatedDailySolarEnergy;

        public MonthlySolarData(int month, Double psh, Double ambientTemperature, double totalDailyEnergy,
                                double requiredEnergy, double requiredPower, double temperatureEfficiency,
                                double efficiency, double deratedPower, int numPanels, double estimatedDailySolarEnergy) {
            this.month = month;
            this.psh = (psh != null) ? psh : 0.0; // Set default value of 0.0 if psh is null
            this.ambientTemperature = (ambientTemperature != null) ? ambientTemperature : 0.0; // Set default value of 0.0 if ambientTemperature is null
            this.totalDailyEnergy = totalDailyEnergy;
            this.requiredEnergy = requiredEnergy;
            this.requiredPower = requiredPower;
            this.temperatureEfficiency = temperatureEfficiency;
            this.efficiency = efficiency;
            this.deratedPower = deratedPower;
            this.numPanels = numPanels;
            this.estimatedDailySolarEnergy = estimatedDailySolarEnergy;
        }

        // Getters and Setters
        public int getMonth() {
            return month;
        }

        public void setMonth(int month) {
            this.month = month;
        }

        public Double getPsh() {
            return psh;
        }

        public void setPsh(Double psh) {
            this.psh = psh;
        }

        public Double getAmbientTemperature() {
            return ambientTemperature;
        }

        public void setAmbientTemperature(Double ambientTemperature) {
            this.ambientTemperature = ambientTemperature;
        }

        public double getTotalDailyEnergy() {
            return totalDailyEnergy;
        }

        public void setTotalDailyEnergy(double totalDailyEnergy) {
            this.totalDailyEnergy = totalDailyEnergy;
        }

        public double getRequiredEnergy() {
            return requiredEnergy;
        }

        public void setRequiredEnergy(double requiredEnergy) {
            this.requiredEnergy = requiredEnergy;
        }

        public double getRequiredPower() {
            return requiredPower;
        }

        public void setRequiredPower(double requiredPower) {
            this.requiredPower = requiredPower;
        }

        public double getTemperatureEfficiency() {
            return temperatureEfficiency;
        }

        public void setTemperatureEfficiency(double temperatureEfficiency) {
            this.temperatureEfficiency = temperatureEfficiency;
        }

        public double getEfficiency() {
            return efficiency;
        }

        public void setEfficiency(double efficiency) {
            this.efficiency = efficiency;
        }

        public double getDeratedPower() {
            return deratedPower;
        }

        public void setDeratedPower(double deratedPower) {
            this.deratedPower = deratedPower;
        }

        public int getNumPanels() {
            return numPanels;
        }

        public void setNumPanels(int numPanels) {
            this.numPanels = numPanels;
        }

        public double getEstimatedDailySolarEnergy() {
            return estimatedDailySolarEnergy;
        }

        public void setEstimatedDailySolarEnergy(double estimatedDailySolarEnergy) {
            this.estimatedDailySolarEnergy = estimatedDailySolarEnergy;
        }
    }
}
